import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import React,{useState} from "react";

export default function Home() {
    /**
     * declaration de variable
     */
    const [count,setCount]=useState(0)
    const [todoList,setTodoList] = useState([])
    const [inter,setInter] = useState(" ")
    console.log(count);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
          <h1 className={styles.title}>
             Hello Edson
          </h1>
          <h3>count : {count}</h3>
          <button  onClick={ () => setCount(count+1)}>Button</button>

          <input type="text" onChange={event => setInter(event.target.value)}>Tache</input>

          <button  onClick={ () => setTodoList([...todoList, inter])}>Button</button>


          { todoList.length > 0 &&(
              todoList.map((todo,i) =>{
                  return (
                      <div key={i}>
                          <p>{todo}</p>

                          <button onClick={()=>setTodoList(prevArray=>prevArray.filter(item=>prevArray.indexOf(item)!==i))}>supprimer</button>
                      </div>)
              })
          )}
      </main>
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
